Repository melissay94/GiveBack, pull requests merged in 2020-03, with the labels that each got.

#11 initial commit
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/setupTests.js
  package-lock.json
  server/package.json
Labels: :one: PRIORITY :1st_place_medal:

#12 Update readme
  README.md
  readme_images/create_event_page.png
  readme_images/landing_page.png
  readme_images/login_page.png
  readme_images/organization_page.png
  readme_images/project_site_map.png
  readme_images/search_results.png
  readme_images/signup_page.png
  readme_images/user_home_page.png
Labels: :page_facing_up: documentation :pencil2:

#19 Add sass
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/scss/App.scss
Labels: :art: Front End, :fire: :100: :dancer:

#20 Add pages
  client/public/index.html
  client/src/index.js
  client/src/pages/EditProfileUser.js
  client/src/pages/Home.js
  client/src/pages/Landing.js
  client/src/pages/Login.js
  client/src/pages/OrganizationUser.js
  client/src/pages/ProfileUser.js
  client/src/pages/SearchResultsUser.js
  client/src/pages/SignupUser.js
  client/src/scss/index.scss
Labels: :art: Front End

#35 Logo colors
  client/package-lock.json
  client/package.json
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.js
  client/src/Components/Logo.js
  client/src/assets/giveback_logo.png
  client/src/logo.svg
Labels: :art: Front End

#37 User home page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/EventComponent.js
  client/src/Components/LogNavBar.js
  client/src/Components/Logo.js
  client/src/Components/OrgComponent.js
  client/src/Components/Searchbar.js
  client/src/Components/SideList.js
  client/src/pages/Home.js
  client/src/scss/App.scss
Labels: :art: Front End

#48 Refactor component tree
  client/src/App.js
  client/src/Components/Content.js
  client/src/Components/Footer.js
  client/src/Components/LogNavBar.js
  client/src/Components/Login.js
  client/src/Components/Logo.js
  client/src/Components/PreNavBar.js
  client/src/pages/Landing.js
Labels: :art: Front End

#50 Solved Navigation Issue
  client/src/Components/Content.js
  client/src/Components/Logo.js
Labels: :art: Front End, :bug: Bugs :beetle:

#52 Post auth nav
  client/src/App.js
  client/src/Components/Content.js
  client/src/Components/LogNavBar.js
  client/src/Components/UserSignUp.js
  client/src/pages/Home.js
  client/src/scss/App.scss
Labels: :art: Front End

#55 User search results
  client/src/Components/Searchbar.js
  client/src/hooks/SearchHook.js
  client/src/pages/SearchResultsUser.js
Labels: :art: Front End, :fire: :100: :dancer:

#58 Search page completed
  client/src/Components/SearchResList.js
  client/src/pages/SearchResultsUser.js
Labels: :art: Front End

#59 User profile
  client/src/Components/Content.js
  client/src/pages/ProfileUser.js
Labels: :art: Front End

#61 Added organization page layout
  client/src/Components/Content.js
  client/src/pages/OrganizationUser.js
Labels: :art: Front End

#79 Some some bugs
  client/src/Components/EditProfile.js
  client/src/pages/OrganizationUser.js
Labels: :bug: Bugs :beetle:

#80 Get user home
  client/src/Components/Content.js
  client/src/Components/EditProfile.js
  client/src/pages/Home.js
Labels: :art: Front End

#81 Added user infomration calls to profile
  client/src/Components/Content.js
  client/src/Components/EditProfile.js
  client/src/pages/EditProfileUser.js
  client/src/pages/ProfileUser.js
Labels: :art: Front End

#83 Added base for getting events, still need endpoint and base url
  client/src/Components/ErrorMessage.js
  client/src/pages/Home.js
Labels: :art: Front End

#85 Get user organizations home
  client/src/pages/Home.js
Labels: :art: Front End

#91 Get organization
  client/src/Components/Content.js
  client/src/Components/OrgComponent.js
  client/src/Components/UserSignUp.js
  client/src/pages/Home.js
  client/src/pages/OrganizationUser.js
Labels: :art: Front End

#92 Added credit to meet out
  README.md
Labels: :page_facing_up: documentation :pencil2:

#98 Search bug fixes
  client/src/pages/SearchResultsUser.js
Labels: :art: Front End, :bug: Bugs :beetle:

#99 Show events home
  client/src/Components/OrgComponent.js
  client/src/Components/SideList.js
  client/src/pages/Home.js
  server/models/event.js
  server/models/organization.js
  server/models/user.js
  server/routes/auth.js
  server/routes/users.js
  server/seedDB.js
Labels: :art: Front End, :bug: Bugs :beetle:, :computer: Back End

#101 You can see events and organizations in search
  client/src/Components/EventComponent.js
  client/src/Components/OrgComponent.js
  client/src/Components/SearchResList.js
  client/src/pages/ProfileUser.js
  client/src/pages/SearchResultsUser.js
  server/routes/events.js
  server/routes/organizations.js
Labels: :art: Front End, :computer: Back End

#110 Added some design to landing page
  README.md
  client/src/Components/Hero.js
  client/src/assets/volunteers.jpg
  client/src/scss/App.scss
Labels: :art: Front End

#111 Design footer
  client/src/App.js
  client/src/Components/Footer.js
  client/src/Components/Hero.js
  client/src/pages/Landing.js
  client/src/scss/App.scss
Labels: :art: Front End

#112 Created some new components and renamed others to help with design
  client/src/Components/EventHomeItem.js
  client/src/Components/EventList.js
  client/src/Components/EventSearchItem.js
  client/src/Components/OrgHomeItem.js
  client/src/Components/OrgList.js
  client/src/Components/OrgSearchItem.js
  client/src/Components/SearchResList.js
  client/src/Components/SideList.js
  client/src/pages/Home.js
  client/src/pages/OrganizationUser.js
Labels: :art: Front End

#113 Design home
  client/src/Components/Calendar.js
  client/src/Components/EventHomeItem.js
  client/src/Components/EventList.js
  client/src/Components/OrgHomeItem.js
  client/src/Components/OrgList.js
  client/src/pages/Home.js
Labels: :art: Front End

#114 Added organization specific data to show up and add to user
  client/src/Components/OrgSearchItem.js
  client/src/pages/OrganizationUser.js
  server/routes/organizations.js
  server/routes/users.js
Labels: :art: Front End

#115 Design search
  client/src/Components/EventSearchItem.js
  client/src/Components/OrgSearchItem.js
  client/src/pages/SearchResultsUser.js
Labels: :art: Front End
